export type ChallengeCategory = 'student' | 'fitness' | 'creator'

export interface Challenge {
  text: string
  category: ChallengeCategory
}

export const challenges: Challenge[] = [
  // Student Mode (165 challenges)
  { text: "Problem solving: solve X problems, do X practice problems, etc", category: "student" },
  { text: "Revision: review past notes, review flashcards, review previous exam questions, etc", category: "student" },
  { text: "Focus: work without distractions, set a timer for X minutes, etc", category: "student" },
  { text: "Read 5 pages of your textbook", category: "student" },
  { text: "Solve 3 math problems", category: "student" },
  { text: "Review flashcards for 10 minutes", category: "student" },
  { text: "Write down 5 key points from the lecture notes", category: "student" },
  { text: "Practice 10 spelling words", category: "student" },
  { text: "Let's create a list of 200", category: "student" },
  { text: "We'll write them in the order that flows naturally", category: "student" },
  { text: "Let's start:", category: "student" },
  { text: "Solve 5 math problems", category: "student" },
  { text: "Read 10 pages of your textbook", category: "student" },
  { text: "Review flashcards for 15 minutes", category: "student" },
  { text: "Write down 5 key points from your notes", category: "student" },
  { text: "Solve 3 physics problems", category: "student" },
  { text: "Read 5 pages of your science textbook", category: "student" },
  { text: "Review past exam questions for 20 minutes", category: "student" },
  { text: "Create a study schedule for the next week", category: "student" },
  { text: "Solve 4 algebra problems", category: "student" },
  { text: "Different subjects: math, science, history, language, etc", category: "student" },
  { text: "Different types of tasks: reading, writing, solving, reviewing, practicing, etc", category: "student" },
  { text: "Different time frames: 5 minutes, 10 minutes, 15 minutes, 20 minutes, 30 minutes, etc", category: "student" },
  { text: "We'll create a list of 200 challenges by:", category: "student" },
  { text: "We'll write 200 lines without any extra text", category: "student" },
  { text: "We'll vary the subject (if applicable) and the action", category: "student" },
  { text: "Let's create the list", category: "student" },
  { text: "I'll write 200 lines", category: "student" },
  { text: "But the problem says: cover reading, notes, problem solving, revision, exam prep, focus", category: "student" },
  { text: "Problem solving: 40", category: "student" },
  { text: "Revision: 30", category: "student" },
  { text: "I'll create a list of 200 strings", category: "student" },
  { text: "We'll start:", category: "student" },
  { text: "Write a summary of 1 paragraph from your reading", category: "student" },
  { text: "Practice 5 vocabulary words", category: "student" },
  { text: "Review your notes for 10 minutes", category: "student" },
  { text: "Solve 2 geometry problems", category: "student" },
  { text: "Read 3 pages of a history textbook", category: "student" },
  { text: "Make flashcards for 5 terms", category: "student" },
  { text: "Review your flashcards for 10 minutes", category: "student" },
  { text: "Solve 1 calculus problem", category: "student" },
  { text: "Write down 3 main ideas from your lecture", category: "student" },
  { text: "Practice 10 history dates", category: "student" },
  { text: "Read 8 pages of your literature textbook", category: "student" },
  { text: "Review your notes for 15 minutes", category: "student" },
  { text: "Solve 5 chemistry problems", category: "student" },
  { text: "Write a short essay on one topic", category: "student" },
  { text: "Practice 10 math problems", category: "student" },
  { text: "Review flashcards for 5 minutes", category: "student" },
  { text: "Solve 3 biology problems", category: "student" },
  { text: "Read 7 pages of your science textbook", category: "student" },
  { text: "Create a mind map for a topic", category: "student" },
  { text: "Write down 10 definitions for terms", category: "student" },
  { text: "Review past exam questions for 10 minutes", category: "student" },
  { text: "Solve 2 algebra problems", category: "student" },
  { text: "Read 4 pages of your history textbook", category: "student" },
  { text: "Make flashcards for 3 terms", category: "student" },
  { text: "Review your notes for 5 minutes", category: "student" },
  { text: "Solve 1 physics problem", category: "student" },
  { text: "Write down 6 key points from a lecture", category: "student" },
  { text: "Read 2 pages of your literature textbook", category: "student" },
  { text: "Solve 4 math problems", category: "student" },
  { text: "Write a summary of 2 paragraphs", category: "student" },
  { text: "Solve 3 chemistry problems", category: "student" },
  { text: "Read 6 pages of your science textbook", category: "student" },
  { text: "Create a study schedule for the next day", category: "student" },
  { text: "Write down 8 key points from your notes", category: "student" },
  { text: "Practice 10 history facts", category: "student" },
  { text: "Solve 1 algebra problem", category: "student" },
  { text: "Read 3 pages of your literature textbook", category: "student" },
  { text: "Write a short paragraph on a topic", category: "student" },
  { text: "Practice 5 spelling words", category: "student" },
  { text: "Read 5 pages of your history textbook", category: "student" },
  { text: "Solve 2 chemistry problems", category: "student" },
  { text: "Write down 4 key points from a lecture", category: "student" },
  { text: "Practice 10 vocabulary words", category: "student" },
  { text: "Solve 1 biology problem", category: "student" },
  { text: "Write a summary of 1 paragraph", category: "student" },
  { text: "Practice 5 history dates", category: "student" },
  { text: "Solve 3 algebra problems", category: "student" },
  { text: "Write down 6 key points from your notes", category: "student" },
  { text: "Solve 2 physics problems", category: "student" },
  { text: "Review past exam questions for 15 minutes", category: "student" },
  { text: "Write down 5 key points from a lecture", category: "student" },
  { text: "Make flashcards for 4 terms", category: "student" },
  { text: "Write down 7 key points from a lecture", category: "student" },
  { text: "Read 4 pages of your science textbook", category: "student" },
  { text: "Solve 1 math problem", category: "student" },
  { text: "Read 6 pages of your history textbook", category: "student" },
  { text: "Read 3 pages of your science textbook", category: "student" },
  { text: "Read 1 page of your literature textbook", category: "student" },
  { text: "Solve 1 geometry problem", category: "student" },
  { text: "Line 5: \"Practice 10 spelling words\"", category: "student" },
  { text: "I'll write the list without duplicates", category: "student" },
  { text: "But I'm doing it manually", category: "student" },
  { text: "I'll create a list of 200 unique phrases", category: "student" },
  { text: "We'll go step by step and avoid repeating", category: "student" },
  { text: "Templates:", category: "student" },
  { text: "But the subject can be: math, science, history, literature, vocabulary, spelling, etc", category: "student" },
  { text: "We'll have 200", category: "student" },
  { text: "We'll avoid:", category: "student" },
  { text: "We'll vary:", category: "student" },
  { text: "I'll write 200 unique lines", category: "student" },
  { text: "We'll output:", category: "student" },
  { text: "I'll write the list as the answer", category: "student" },
  { text: "Let's output:", category: "student" },
  { text: "Read 3 pages of your history textbook", category: "student" },
  { text: "Read 7 pages of your literature textbook", category: "student" },
  { text: "Read 2 pages of your science textbook", category: "student" },
  { text: "Write down 8 key points from a lecture", category: "student" },
  { text: "Read 5 pages of your literature textbook", category: "student" },
  { text: "Read 1 page of your history textbook", category: "student" },
  { text: "Solve 4 calculus problems", category: "student" },
  { text: "Read 2 pages of your history textbook", category: "student" },
  { text: "Solve 10 quadratic equations with integer coefficients", category: "student" },
  { text: "Identify 5 examples of chemical reactions in daily life", category: "student" },
  { text: "List 3 causes of the French Revolution with dates", category: "student" },
  { text: "Translate 15 sentences from English to Spanish", category: "student" },
  { text: "Draw a detailed flowchart of the water cycle", category: "student" },
  { text: "Calculate the area of 5 irregular shapes using geometry formulas", category: "student" },
  { text: "Memorize 10 key historical figures from the Industrial Revolution", category: "student" },
  { text: "Write 5 sentences using passive voice in English", category: "student" },
  { text: "Solve 8 systems of linear equations with substitution", category: "student" },
  { text: "Create a timeline of the American Civil War with key events", category: "student" },
  { text: "Label 5 parts of a cell diagram correctly", category: "student" },
  { text: "Practice 20 minutes of silent reading with focus", category: "student" },
  { text: "Solve 12 basic calculus differentiation problems", category: "student" },
  { text: "Identify 7 types of rocks and their formation processes", category: "student" },
  { text: "Write 10 historical events that shaped modern democracy", category: "student" },
  { text: "Translate 10 German vocabulary words to English", category: "student" },
  { text: "Calculate the volume of 5 3D shapes using standard formulas", category: "student" },
  { text: "Memorize the first 20 elements of the periodic table", category: "student" },
  { text: "Solve 15 algebraic word problems involving rates", category: "student" },
  { text: "Create a concept map of photosynthesis with 5 key steps", category: "student" },
  { text: "Write 5 sentences describing the impact of the Black Death", category: "student" },
  { text: "Solve 7 trigonometric equations for acute angles", category: "student" },
  { text: "Identify 3 major scientific theories from the 20th century", category: "student" },
  { text: "Memorize 15 French verb conjugations in present tense", category: "student" },
  { text: "Calculate the probability of 5 simple independent events", category: "student" },
  { text: "Outline the causes and effects of the Treaty of Versailles", category: "student" },
  { text: "Solve 10 linear inequalities graphically", category: "student" },
  { text: "Write 5 sentences about the causes of World War I", category: "student" },
  { text: "Identify 5 functions of the human nervous system", category: "student" },
  { text: "Translate 12 sentences from Chinese to English", category: "student" },
  { text: "Solve 8 quadratic equations using the quadratic formula", category: "student" },
  { text: "Create a mind map of the digestive system with 4 layers", category: "student" },
  { text: "Write 10 historical dates related to the Renaissance period", category: "student" },
  { text: "Solve 15 basic physics problems involving motion", category: "student" },
  { text: "Memorize 15 key terms in the theory of relativity", category: "student" },
  { text: "Practice 20 minutes of focused writing without distractions", category: "student" },
  { text: "Identify 5 common acids and bases in household items", category: "student" },
  { text: "Write 5 sentences describing the Industrial Revolution's impact", category: "student" },
  { text: "Solve 12 algebraic equations for one variable", category: "student" },
  { text: "Create a timeline of the American Revolution with 5 battles", category: "student" },
  { text: "Translate 10 Spanish sentences into English using simple vocabulary", category: "student" },
  { text: "Calculate the mean, median, and mode for 5 datasets", category: "student" },
  { text: "Identify 3 major geological features and their locations", category: "student" },
  { text: "Write 10 sentences about the causes of the Cold War", category: "student" },
  { text: "Solve 7 problems involving simple interest calculations", category: "student" },
  { text: "Create a concept map of cellular respiration with 4 stages", category: "student" },
  { text: "Memorize 15 key vocabulary terms for the French Revolution", category: "student" },
  { text: "Solve 10 problems using the Pythagorean theorem", category: "student" },
  { text: "Write 5 sentences about the causes of the American Civil War", category: "student" },
  { text: "Identify 5 types of energy transformations in nature", category: "student" },
  { text: "Practice 15 minutes of focused reading without notes", category: "student" },

  // Fitness Mode (188 challenges)
  { text: "For strength:", category: "fitness" },
  { text: "We'll create a list of 200 challenges by having:", category: "fitness" },
  { text: "We'll write the challenges in a way that they are unique", category: "fitness" },
  { text: "Strength (25):", category: "fitness" },
  { text: "Do 10 push-ups", category: "fitness" },
  { text: "Do 15 squats", category: "fitness" },
  { text: "Do 12 bodyweight lunges", category: "fitness" },
  { text: "Do 8 push-ups with knees", category: "fitness" },
  { text: "Actually, the examples:", category: "fitness" },
  { text: "We'll write without hyphen: \"pushups\", \"plank\", \"walk\", etc", category: "fitness" },
  { text: "Let's create a list of 200", category: "fitness" },
  { text: "Do 10 pushups", category: "fitness" },
  { text: "Do 8 pushups with knees", category: "fitness" },
  { text: "Cardio (25):", category: "fitness" },
  { text: "Go for a 5-minute run", category: "fitness" },
  { text: "Do 10 jumping jacks", category: "fitness" },
  { text: "Do 30 high knees", category: "fitness" },
  { text: "Do 20 mountain climbers", category: "fitness" },
  { text: "Do 10 jumping jacks with a 10-second rest", category: "fitness" },
  { text: "Stretching (25):", category: "fitness" },
  { text: "Hold a hamstring stretch for 30 seconds", category: "fitness" },
  { text: "Hold a quad stretch for 20 seconds", category: "fitness" },
  { text: "Do 10 child's pose holds", category: "fitness" },
  { text: "Do 15 seated forward bends", category: "fitness" },
  { text: "Yoga (25):", category: "fitness" },
  { text: "Hold downward dog for 45 seconds", category: "fitness" },
  { text: "Hold child's pose for 30 seconds", category: "fitness" },
  { text: "Do 10 warrior poses", category: "fitness" },
  { text: "Core (25):", category: "fitness" },
  { text: "Do 10 Russian twists", category: "fitness" },
  { text: "Do 15 hollow body holds", category: "fitness" },
  { text: "Balance (25):", category: "fitness" },
  { text: "Stand on one foot for 30 seconds", category: "fitness" },
  { text: "Do 10 single-leg stands", category: "fitness" },
  { text: "Mobility (25):", category: "fitness" },
  { text: "Do 10 arm circles for 15 seconds", category: "fitness" },
  { text: "Do 15 ankle circles for 20 seconds", category: "fitness" },
  { text: "Breathing (25):", category: "fitness" },
  { text: "Breathe in for 4 counts, hold for 7, out for 8", category: "fitness" },
  { text: "Do 1 minute of diaphragmatic breathing", category: "fitness" },
  { text: "Bodyweight (25):", category: "fitness" },
  { text: "How about we do:", category: "fitness" },
  { text: "We'll write a list and then remove duplicates and count until 200", category: "fitness" },
  { text: "We'll create a list of challenges in Python (in mind) and then output", category: "fitness" },
  { text: "Start with strength (25):", category: "fitness" },
  { text: "Do 10 glute bridges", category: "fitness" },
  { text: "Do 15 reverse lunges", category: "fitness" },
  { text: "Do 10 diamond push-ups", category: "fitness" },
  { text: "Do 12 side planks", category: "fitness" },
  { text: "Do 10 bird-dogs", category: "fitness" },
  { text: "Do 15 planks", category: "fitness" },
  { text: "Do 10 mountain climbers", category: "fitness" },
  { text: "Let's skip the hard ones and do:", category: "fitness" },
  { text: "Do 12 lunges", category: "fitness" },
  { text: "Do 5 bodyweight overhead presses", category: "fitness" },
  { text: "Do 10 bodyweight rows", category: "fitness" },
  { text: "Do 15 reverse crunches", category: "fitness" },
  { text: "Do 10 leg raises", category: "fitness" },
  { text: "Do 12 wall sits", category: "fitness" },
  { text: "Do 10 burpees", category: "fitness" },
  { text: "Do 15 jumping jacks", category: "fitness" },
  { text: "Do 10 bodyweight squats", category: "fitness" },
  { text: "Do 12 bodyweight push-ups (with hands on floor)", category: "fitness" },
  { text: "Do 10 bodyweight squats with a step", category: "fitness" },
  { text: "Do 15 bodyweight step-ups", category: "fitness" },
  { text: "Do 10 bodyweight step-downs", category: "fitness" },
  { text: "After generating 25 strength, we do:", category: "fitness" },
  { text: "Do 10 jump rope (30 seconds)", category: "fitness" },
  { text: "Go for a 10-minute walk", category: "fitness" },
  { text: "Do 15 high knees", category: "fitness" },
  { text: "Do 20 jumping jacks", category: "fitness" },
  { text: "Go for a 7-minute jog", category: "fitness" },
  { text: "Go for a 15-minute run", category: "fitness" },
  { text: "Do 30 high knees (with 10 seconds rest)", category: "fitness" },
  { text: "We'll write:", category: "fitness" },
  { text: "Do 10 cat-cow stretches", category: "fitness" },
  { text: "Hold a triceps stretch for 25 seconds", category: "fitness" },
  { text: "Hold a shoulder stretch for 30 seconds", category: "fitness" },
  { text: "Do 10 neck stretches", category: "fitness" },
  { text: "Do 15 ankle stretches", category: "fitness" },
  { text: "Hold a hip flexor stretch for 20 seconds", category: "fitness" },
  { text: "Do 10 chest stretches", category: "fitness" },
  { text: "Hold a calf stretch for 30 seconds", category: "fitness" },
  { text: "Do 10 deep breath stretches", category: "fitness" },
  { text: "Do 10 hamstring stretches", category: "fitness" },
  { text: "Do 15 quad stretches", category: "fitness" },
  { text: "Do 10 shoulder stretches", category: "fitness" },
  { text: "Do 15 ankle circles", category: "fitness" },
  { text: "Do 10 neck rotations", category: "fitness" },
  { text: "Hold a hip stretch for 20 seconds", category: "fitness" },
  { text: "Do 15 deep breathing stretches", category: "fitness" },
  { text: "Do 10 seated stretches", category: "fitness" },
  { text: "Do 15 standing stretches", category: "fitness" },
  { text: "Do 15 tree pose holds", category: "fitness" },
  { text: "Hold a bridge pose for 20 seconds", category: "fitness" },
  { text: "Do 10 boat pose holds", category: "fitness" },
  { text: "Hold a half-moon pose for 25 seconds", category: "fitness" },
  { text: "Do 15 child's pose", category: "fitness" },
  { text: "Hold a cobra pose for 30 seconds", category: "fitness" },
  { text: "Do 10 seated forward bends", category: "fitness" },
  { text: "Hold a pigeon pose for 20 seconds", category: "fitness" },
  { text: "Do 15 knee-to-chest stretches", category: "fitness" },
  { text: "Hold a lizard pose for 25 seconds", category: "fitness" },
  { text: "Do 10 seated spinal twists", category: "fitness" },
  { text: "Hold a fish pose for 30 seconds", category: "fitness" },
  { text: "Do 10 eagle pose holds", category: "fitness" },
  { text: "Hold a warrior III for 20 seconds", category: "fitness" },
  { text: "Do 15 deep breathing in yoga", category: "fitness" },
  { text: "Hold a triangle pose for 30 seconds", category: "fitness" },
  { text: "Do 10 sun salutations", category: "fitness" },
  { text: "Do 15 seated twists", category: "fitness" },
  { text: "Hold a downward-facing dog for 45 seconds", category: "fitness" },
  { text: "Do 10 bridge pose", category: "fitness" },
  { text: "Do 10 reverse crunches", category: "fitness" },
  { text: "Do 15 bird-dogs", category: "fitness" },
  { text: "Do 10 plank holds", category: "fitness" },
  { text: "Do 15 leg raises", category: "fitness" },
  { text: "Do 10 dead bugs", category: "fitness" },
  { text: "Do 12 seated twists", category: "fitness" },
  { text: "Do 15 bicycle crunches", category: "fitness" },
  { text: "Do 10 mountain climbers for core", category: "fitness" },
  { text: "Do 15 plank holds", category: "fitness" },
  { text: "Do 15 standing on one foot", category: "fitness" },
  { text: "Hold a single-leg balance for 20 seconds", category: "fitness" },
  { text: "Do 10 balance holds on each foot", category: "fitness" },
  { text: "Do 15 eyes closed balance", category: "fitness" },
  { text: "Do 10 single-leg squats", category: "fitness" },
  { text: "Do 15 balance on one foot", category: "fitness" },
  { text: "Do 10 walking on a straight line", category: "fitness" },
  { text: "Do 15 standing on one foot with eyes closed", category: "fitness" },
  { text: "Do 10 single-leg stands with arms up", category: "fitness" },
  { text: "Do 15 balance on one foot with eyes closed", category: "fitness" },
  { text: "Do 10 single-leg holds", category: "fitness" },
  { text: "Do 15 balance on one foot without moving", category: "fitness" },
  { text: "Do 10 single-leg raises", category: "fitness" },
  { text: "Do 15 walking on tiptoes", category: "fitness" },
  { text: "Do 10 single-leg balances with eyes closed", category: "fitness" },
  { text: "Do 15 standing on one foot with arms out", category: "fitness" },
  { text: "Do 10 single-leg holds with eyes closed", category: "fitness" },
  { text: "Do 15 balance on one foot with hands on hips", category: "fitness" },
  { text: "Do 10 single-leg holds with eyes open", category: "fitness" },
  { text: "Do 15 single-leg stands with eyes closed", category: "fitness" },
  { text: "Do 10 single-leg balances with arms up", category: "fitness" },
  { text: "Do 3 sets of 10 tricep dips", category: "fitness" },
  { text: "Do 20 high knees", category: "fitness" },
  { text: "Sprint in place for 30 seconds", category: "fitness" },
  { text: "Do 10 single-leg glute bridges each side", category: "fitness" },
  { text: "Do 15 side lateral raises with arms", category: "fitness" },
  { text: "Hold a deep squat for 30 seconds", category: "fitness" },
  { text: "Do 10 inchworms", category: "fitness" },
  { text: "Do 20 toe touches", category: "fitness" },
  { text: "Do 10 reverse hyperextensions", category: "fitness" },
  { text: "Do 15 standing knee raises each leg", category: "fitness" },
  { text: "Do 30 seconds of mountain climbers", category: "fitness" },
  { text: "Do 10 slow negative pushups", category: "fitness" },
  { text: "Do 20 flutter kicks", category: "fitness" },
  { text: "Do 10 scapular pushups", category: "fitness" },
  { text: "Do 15 glute kickbacks each leg", category: "fitness" },
  { text: "Do 3 sets of 5 slow pushups", category: "fitness" },
  { text: "Do 20 ankle circles each foot", category: "fitness" },
  { text: "Do 10 hip circles each direction", category: "fitness" },
  { text: "Hold a wall sit for 45 seconds", category: "fitness" },
  { text: "Do 15 standing oblique crunches each side", category: "fitness" },
  { text: "Do 10 bear crawl steps forward and back", category: "fitness" },
  { text: "Do 20 calf raises on one leg each side", category: "fitness" },
  { text: "Do 10 pike pushups", category: "fitness" },
  { text: "Do 15 supermans", category: "fitness" },
  { text: "Do 30 second side plank each side", category: "fitness" },
  { text: "Do 10 lateral lunges each side", category: "fitness" },
  { text: "Do 20 arm circles each direction", category: "fitness" },
  { text: "Do 10 bodyweight good mornings", category: "fitness" },
  { text: "Do 15 hamstring curls standing", category: "fitness" },
  { text: "Do 10 tuck jumps", category: "fitness" },
  { text: "Do 20 standing hip abductions each side", category: "fitness" },
  { text: "Do 3 sets of max pushups to failure", category: "fitness" },
  { text: "Do 10 slow mountain climbers each leg", category: "fitness" },
  { text: "Do 20 alternating leg raises", category: "fitness" },
  { text: "Do 15 cobra stretches", category: "fitness" },
  { text: "Do 10 downward dog to upward dog flows", category: "fitness" },
  { text: "Do 20 wrist circles each direction", category: "fitness" },
  { text: "Do 10 broad jumps", category: "fitness" },
  { text: "Do 3 rounds of 10 air squats + 5 pushups", category: "fitness" },
  { text: "Do 15 seated leg extensions", category: "fitness" },
  { text: "Do 10 reverse lunges with knee drive", category: "fitness" },
  { text: "Do 20 heel-to-toe walks", category: "fitness" },
  { text: "Do 15 shoulder rolls each direction", category: "fitness" },
  { text: "Do 10 jump squats", category: "fitness" },
  { text: "Do 30 seconds of skipping in place", category: "fitness" },

  // Creator Mode (188 challenges)
  { text: "Write a program that converts a string to its SHA-256 hash", category: "creator" },
  { text: "Build a command-line tool that checks for duplicate files in a directory", category: "creator" },
  { text: "Implement a simple REST API that returns the current time in UTC", category: "creator" },
  { text: "Write a script that automates the process of renaming files in a folder by adding a timestamp", category: "creator" },
  { text: "Create a Python module that validates email addresses", category: "creator" },
  { text: "Build a simple web scraper that extracts all links from a webpage", category: "creator" },
  { text: "Create a function that reverses a string without using built-in functions", category: "creator" },
  { text: "Build a command-line tool that converts a CSV file to JSON", category: "creator" },
  { text: "Implement a simple chat application using sockets", category: "creator" },
  { text: "Write a script that monitors the disk usage of a system", category: "creator" },
  { text: "Build a tool that converts a string to a list of words with their part-of-speech tags", category: "creator" },
  { text: "Create a function that removes all vowels from a string", category: "creator" },
  { text: "Implement a simple database schema for a to-do list application", category: "creator" },
  { text: "Write a script that compresses a folder using ZIP", category: "creator" },
  { text: "Build a command-line tool that converts a hexadecimal string to ASCII", category: "creator" },
  { text: "Create a function that checks for palindromes in a string", category: "creator" },
  { text: "Build a simple calculator that supports basic arithmetic operations", category: "creator" },
  { text: "Write a script that counts the occurrences of a specific character in a file", category: "creator" },
  { text: "Implement a simple HTTP server that serves static files", category: "creator" },
  { text: "Build a tool that converts a date string to a specific format", category: "creator" },
  { text: "Write a program that finds the longest common substring between two strings", category: "creator" },
  { text: "Writing challenges (30):", category: "creator" },
  { text: "Write a story about a cat that can speak in 200 words", category: "creator" },
  { text: "Write a haiku that describes the feeling of loneliness", category: "creator" },
  { text: "Compose a poem with 5 stanzas and a rhyme scheme of ABAB", category: "creator" },
  { text: "Write a short dialogue between two characters that resolves a conflict in 150 words", category: "creator" },
  { text: "Craft a letter to a future self about your dreams in 250 words", category: "creator" },
  { text: "Write a paragraph that describes a day in the life of a robot in 100 words", category: "creator" },
  { text: "Create a fictional character profile with 10 key traits in 150 words", category: "creator" },
  { text: "Write an essay on the importance of sleep for children in 200 words", category: "creator" },
  { text: "Compose a short story with a twist ending in 300 words", category: "creator" },
  { text: "Write a letter of apology to a friend in 150 words", category: "creator" },
  { text: "Create a news article about a local event in 250 words", category: "creator" },
  { text: "Write a poem that uses the word \"light\" in every line", category: "creator" },
  { text: "Craft a dialogue between a programmer and a designer about their work in 100 words", category: "creator" },
  { text: "Write a description of a dream you had last night in 150 words", category: "creator" },
  { text: "Create a short narrative about a lost object in 200 words", category: "creator" },
  { text: "Write a letter to your future self in 100 words", category: "creator" },
  { text: "Compose a story about a person who never learns to read in 150 words", category: "creator" },
  { text: "Write a paragraph about the color blue in 100 words", category: "creator" },
  { text: "Create a short story about a robot that falls in love in 200 words", category: "creator" },
  { text: "Write a letter to a stranger that you've never met in 150 words", category: "creator" },
  { text: "Craft a description of a city at night in 200 words", category: "creator" },
  { text: "Write a poem about the changing seasons in 150 words", category: "creator" },
  { text: "Create a short story about a person who finds a time machine in 200 words", category: "creator" },
  { text: "Write a paragraph about the meaning of freedom in 100 words", category: "creator" },
  { text: "Compose a story about a child's first day at school in 150 words", category: "creator" },
  { text: "Write a letter to your best friend that you haven't spoken to in years in 200 words", category: "creator" },
  { text: "Create a short story about a person who becomes a ghost in 200 words", category: "creator" },
  { text: "Write a description of a day in the life of a squirrel in 100 words", category: "creator" },
  { text: "Craft a paragraph about the ocean in 150 words", category: "creator" },
  { text: "Write a story about a person who meets their future self in 200 words", category: "creator" },
  { text: "Design challenges (20):", category: "creator" },
  { text: "Sketch a mobile app interface for a food delivery service", category: "creator" },
  { text: "Design a user flow for a budgeting app", category: "creator" },
  { text: "Create a wireframe for a social media platform", category: "creator" },
  { text: "Draw a style guide for a tech company's website", category: "creator" },
  { text: "Design a logo for a startup that sells eco-friendly products", category: "creator" },
  { text: "Sketch an interface for a virtual reality game", category: "creator" },
  { text: "Create a color palette for a wellness app", category: "creator" },
  { text: "Design a prototype for a fitness tracker", category: "creator" },
  { text: "Draw a user interface for a video conferencing tool", category: "creator" },
  { text: "Sketch a dashboard for a financial dashboard", category: "creator" },
  { text: "Design a landing page for a new product launch", category: "creator" },
  { text: "Create a flowchart for a user onboarding process", category: "creator" },
  { text: "Sketch an icon set for a weather app", category: "creator" },
  { text: "Design a mobile app for a language learning platform", category: "creator" },
  { text: "Create a style guide for a children's book website", category: "creator" },
  { text: "Sketch an interface for a task management application", category: "creator" },
  { text: "Design a prototype for a habit tracking app", category: "creator" },
  { text: "Draw a wireframe for a shopping cart on an e-commerce site", category: "creator" },
  { text: "Create a layout for a news website that is accessible for colorblind users", category: "creator" },
  { text: "Design a simple animation for a mobile app", category: "creator" },
  { text: "Journaling challenges (10):", category: "creator" },
  { text: "Journal about a challenge you faced today in 100 words", category: "creator" },
  { text: "Write down three things you are grateful for in 50 words", category: "creator" },
  { text: "Reflect on a decision you made today and its consequences in 150 words", category: "creator" },
  { text: "Describe a place you visited this week in 100 words", category: "creator" },
  { text: "Write about a dream you had last night in 50 words", category: "creator" },
  { text: "Journal about a feeling of anxiety and how you managed it in 100 words", category: "creator" },
  { text: "List five small habits you want to improve this week in 50 words", category: "creator" },
  { text: "Write about a conversation you had today that changed your perspective in 100 words", category: "creator" },
  { text: "Reflect on a mistake you made and what you learned in 150 words", category: "creator" },
  { text: "Journal about a moment of joy in your day in 50 words", category: "creator" },
  { text: "Brainstorming challenges (10):", category: "creator" },
  { text: "Brainstorm 10 creative uses for a rubber band", category: "creator" },
  { text: "Brainstorm a list of 5 problems that could be solved by AI in 2024", category: "creator" },
  { text: "Brainstorm 5 innovative ways to reduce plastic waste in a city", category: "creator" },
  { text: "Brainstorm 10 unique names for a new tech startup", category: "creator" },
  { text: "Brainstorm a solution to the problem of traffic congestion in a major city", category: "creator" },
  { text: "Brainstorm 5 ways to make learning a language more fun for children", category: "creator" },
  { text: "Brainstorm 10 ideas for a mobile game that teaches coding", category: "creator" },
  { text: "Create a story where every character's name is a programming language", category: "creator" },
  { text: "Design a website that works only on Tuesdays", category: "creator" },
  { text: "Write a poem that describes the life cycle of a computer virus", category: "creator" },
  { text: "Build a robot that can only speak in emojis", category: "creator" },
  { text: "Create a set of instructions for assembling a chair using only the sound of your voice", category: "creator" },
  { text: "Design an app that predicts your future based on your current social media activity", category: "creator" },
  { text: "Write a letter to your future self in the year 2050", category: "creator" },
  { text: "Create a map of the internet using only the colors of the rainbow", category: "creator" },
  { text: "Design a game where you must solve puzzles using only your left hand", category: "creator" },
  { text: "Write a haiku that describes the feeling of debugging code", category: "creator" },
  { text: "Create instructions for assembling a chair using only the sound of your voice", category: "creator" },
  { text: "Invent a programming language that has only one command: 'sleep'", category: "creator" },
  { text: "Design a user interface that changes color with your mood", category: "creator" },
  { text: "Write a short story where the protagonist is a cloud", category: "creator" },
  { text: "Create a set of rules for a game where everyone must use the same word for their entire game", category: "creator" },
  { text: "Design a poster that explains quantum computing in 50 words using only pictures", category: "creator" },
  { text: "Write a song where each line is a different programming error message", category: "creator" },
  { text: "Create a physical object that can only be interacted with through sound waves", category: "creator" },
  { text: "Design a mobile app that turns your voice into a painting", category: "creator" },
  { text: "Write a diary entry from the perspective of a keyboard", category: "creator" },
  { text: "Build a bridge that can only be crossed by people who have solved a math puzzle", category: "creator" },
  { text: "Create a list of the top 10 most misunderstood programming concepts in 10 words", category: "creator" },
  { text: "Design a game where you have to build a city with only the resources of your imagination", category: "creator" },
  { text: "Write a short story about a programmer who becomes a chef", category: "creator" },
  { text: "Create a set of instructions for building a house using only the materials found in your home", category: "creator" },
  { text: "Design an app that shows the emotional state of a person based on their typing speed", category: "creator" },
  { text: "Write a letter to your future self that is only readable after 10 years", category: "creator" },
  { text: "Build a robot that can only communicate in the language of your childhood", category: "creator" },
  { text: "Create a map of the world using only the colors that you can see in your dreams", category: "creator" },
  { text: "Design a game where you must find the hidden meaning in the background of a painting", category: "creator" },
  { text: "Write a poem that describes the life of a single line of code", category: "creator" },
  { text: "Create a system that automatically detects when you are procrastinating and gives you a small reward", category: "creator" },
  { text: "Design a user interface that changes its layout based on the time of day", category: "creator" },
  { text: "Write a short story about a person who can only speak in binary", category: "creator" },
  { text: "Build a device that can only be controlled by the movement of your eyes", category: "creator" },
  { text: "Create a set of rules for a game where you must use only the letters in your name to spell words", category: "creator" },
  { text: "Design a poster that explains blockchain in 100 words using only symbols", category: "creator" },
  { text: "Write a song that tells the story of a software bug", category: "creator" },
  { text: "Create a physical object that changes color when it is happy or sad", category: "creator" },
  { text: "Design an app that shows the impact of your digital footprint on the environment", category: "creator" },
  { text: "Write a letter from a future robot to its creator", category: "creator" },
  { text: "Create a set of instructions for building a robot that can only do one task: making tea", category: "creator" },
  { text: "Design a game where you must solve puzzles using only your right hand", category: "creator" },
  { text: "Write a haiku about the feeling of being in a loop", category: "creator" },
  { text: "Create a map of the internet that shows the most important connections as roads", category: "creator" },
  { text: "Design an app that turns your thoughts into a visual representation", category: "creator" },
  { text: "Write a story about a programmer who becomes a detective", category: "creator" },
  { text: "Build a bridge that can only be crossed by people who have written a program in the past week", category: "creator" },
  { text: "Create a list of the top 5 most frustrating programming errors in 5 words", category: "creator" },
  { text: "Design a game where you must build a city with only the materials you can find in your kitchen", category: "creator" },
  { text: "Write a short story about a person who can only see in shades of gray", category: "creator" },
  { text: "Create a system that automatically sends you a notification when you have been idle for too long", category: "creator" },
  { text: "Design a user interface that changes color with the weather outside", category: "creator" },
  { text: "Write a poem that describes the feeling of a software update", category: "creator" },
  { text: "Build a robot that can only interact with you through text messages in a specific language", category: "creator" },
  { text: "Design a poster that explains the concept of recursion in 50 words using only pictures", category: "creator" },
  { text: "Write a song that describes the life of a computer virus", category: "creator" },
  { text: "Create a map of the world that shows the most common programming languages", category: "creator" },
  { text: "Write a short story about a programmer who becomes a painter", category: "creator" },
  { text: "Build a device that can only be controlled by the sound of your voice", category: "creator" },
  { text: "Create a set of instructions for building a house using only the materials you have at home", category: "creator" },
  { text: "Design a game where you must solve puzzles using only your left foot", category: "creator" },
  { text: "Write a haiku about the feeling of being stuck in a bug", category: "creator" },
  { text: "Create a map of the internet using only the colors of the rainbow and the shapes of the planets", category: "creator" },
  { text: "Design a user interface that changes its layout based on your current mood", category: "creator" },
  { text: "Write a story about a person who can only speak in code", category: "creator" },
  { text: "Build a system that automatically detects when you are being distracted and gives you a small task", category: "creator" },
  { text: "Create a list of the top 10 most important programming concepts in 10 words", category: "creator" },
  { text: "Design a game where you must build a city with only the resources of your imagination", category: "creator" },
  { text: "Write a poem that describes the life of a server", category: "creator" },
  { text: "Create a set of rules for a game where you must use only the letters in your name to form words", category: "creator" },
  { text: "Build a robot that can only communicate in the language of your dreams", category: "creator" },
  { text: "Write a short story about a person who becomes a programmer after a car accident", category: "creator" },
  { text: "Build a system that automatically sends you a notification when you have been idle for too long", category: "creator" },
  { text: "Design a user interface that changes color with the time of day", category: "creator" },
  { text: "Create a set of instructions for building a chair using only the sound of your voice", category: "creator" },
  { text: "Write a story about a programmer who becomes a chef", category: "creator" },
  { text: "Revised list (with 100 unique challenges):", category: "creator" },
  { text: "Create a physical object", category: "creator" },
  { text: "Write a haiku about your current project", category: "creator" },
  { text: "Create a mood board for an app idea", category: "creator" },
  { text: "Write a function that you've been putting off", category: "creator" },
  { text: "List 5 features you'd cut from a product you use", category: "creator" },
  { text: "Draw your ideal workspace", category: "creator" },
  { text: "Write 3 user stories for an app idea", category: "creator" },
  { text: "Refactor one messy function in a project", category: "creator" },
  { text: "Write a README for a project you've abandoned", category: "creator" },
  { text: "Create a color palette for a brand", category: "creator" },
  { text: "Write a cover letter for your dream role", category: "creator" },
  { text: "Sketch a dark mode version of an existing app", category: "creator" },
  { text: "Write one paragraph of technical documentation", category: "creator" },
  { text: "List 10 things you'd automate if you could", category: "creator" },
  { text: "Create a simple landing page wireframe", category: "creator" },
  { text: "Write a changelog entry for an imaginary feature", category: "creator" },
  { text: "Set up a GitHub repo for a new side project", category: "creator" },
  { text: "Write a short how-to guide for something you know well", category: "creator" },
]

export function getRandomChallenge(category?: ChallengeCategory): Challenge {
  const pool = category ? challenges.filter(c => c.category === category) : challenges
  return pool[Math.floor(Math.random() * pool.length)]
}

export const categoryConfig = {
  student: { label: 'Student Mode', emoji: '📚', color: 'from-violet-500 to-purple-600' },
  fitness: { label: 'Fitness Mode', emoji: '💪', color: 'from-emerald-500 to-green-600' },
  creator: { label: 'Creator Mode', emoji: '🎨', color: 'from-orange-500 to-amber-600' },
}
